docs/AboutUs.md, docs/team/caando.md
Issue https://github.com/AY2425S2-CS2103T-F14-4/tp/issues/9
=> feat: Add caando's about us

docs/_config.yml, docs/_data/projects.yml, docs/_sass/minima/_base.scss, docs/index.md
Closes: https://github.com/AY2425S2-CS2103T-F14-4/tp/issues/26
=> Update site settings and content

docs/DeveloperGuide.md
=> Update the DG : Non-functional requirements

docs/Documentation.md, docs/_config.yml, docs/_data/projects.yml, docs/_sass/minima/_base.scss
- Rename instances of `AB-3` to `TrackUp`
- Add `TrackUp` to projects
Closes: https://github.com/AY2425S2-CS2103T-F14-4/tp/issues/26
=> docs: Fully adapt website for TrackUp

docs/DeveloperGuide.md
Updated glossary based on current MVP knowledge 
Closes: https://github.com/AY2425S2-CS2103T-F14-4/tp/issues/25
=> Update DG glossary based on MVP

docs/DeveloperGuide.md
This PR addresses Issue #23 by adding new use cases to the Developer Guide (DG).
Summary of Changes:
Added new use cases for adding, editing a contact as well as viewing all contacts.
Ensured the use case follows the MSS (Main Success Scenario) and Extensions format.
Reformatted existing use cases for clarity and consistency.
Linked Issue:
Fixes #23
Steps to Verify:
Open DeveloperGuide.md
Navigate to the Use Cases section.
Verify that the new use case is correctly formatted and follows the team's documentation style.
=> docs: Add more use cases to DeveloperGuide.md

src/main/java/seedu/address/model/category/Category.java, src/test/java/seedu/address/model/category/CategoryTest.java
=> Add Category class for TrackUp

build.gradle
Closes: https://github.com/AY2425S2-CS2103T-F14-4/tp/issues/61
=> feat: Add mockito for test stubs

docs/UserGuide.md
Closes: https://github.com/AY2425S2-CS2103T-F14-4/tp/issues/39
=> docs: Add DeleteByCommand to UserGuide

build.gradle, src/main/java/seedu/address/logic/commands/DeleteByCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DeleteByCommandParser.java, src/test/java/seedu/address/logic/commands/DeleteByCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/DeleteByCommandParserTest.java
Added DeleteByCommand that allows users to users to delete by any attribute of a person.
Closes: https://github.com/AY2425S2-CS2103T-F14-4/tp/issues/37
=> Feat: Add DeleteByCommand

src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/test/java/seedu/address/testutil/PersonUtil.java
Closes #75 
Edit original command prefixes to have a whitespace at the end
=> Add whitespace to current prefix

docs/DeveloperGuide.md
=> Edit Developer Guide user cases for list command

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/SearchCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/SearchCommandParser.java, src/test/java/seedu/address/logic/commands/SearchCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
Closes: https://github.com/AY2425S2-CS2103T-F14-4/tp/issues/69
Evidence:
search by name string
=> feat: Search command

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/DeleteByCommand.java, src/test/java/seedu/address/logic/commands/DeleteByCommandTest.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java, src/test/java/seedu/address/logic/commands/ListCommandTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/SampleDataUtilTest.java, src/test/java/seedu/address/model/UserPrefsTest.java, src/test/java/seedu/address/model/tag/TagTest.java
Closes: https://github.com/AY2425S2-CS2103T-F14-4/tp/issues/70
=> test: Improve test coverage

src/main/java/trackup/logic/Messages.java, src/main/java/trackup/logic/commands/AddEventCommand.java, src/main/java/trackup/logic/parser/AddEventCommandParser.java, src/main/java/trackup/logic/parser/AddressBookParser.java, src/main/java/trackup/logic/parser/CliSyntax.java, src/main/java/trackup/logic/parser/ParserUtil.java, src/main/java/trackup/model/Model.java, src/main/java/trackup/model/ModelManager.java, src/main/java/trackup/model/event/Event.java, src/test/java/trackup/logic/commands/AddCommandTest.java
Closes #92 
Add AddEventCommand and AddEventCommandParser with relevant classes for them to work properly
=> feat: AddEventCommand and AddEventCommandParser

docs/UserGuide.md
Closes #107 
- Updates UG feature descriptions for add event and delete event command
=> docs: Update UG for events

src/main/java/trackup/logic/commands/DeleteEventCommand.java, src/main/java/trackup/storage/JsonSerializableAddressBook.java, src/test/data/JsonSerializableAddressBookTest/duplicateEventAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalAddressBookWithEvents.json, src/test/java/trackup/logic/commands/AddCommandTest.java, src/test/java/trackup/logic/commands/AddEventCommandTest.java, src/test/java/trackup/logic/commands/CommandTestUtil.java, src/test/java/trackup/logic/commands/DeleteEventCommandTest.java, src/test/java/trackup/logic/parser/AddEventCommandParserTest.java, src/test/java/trackup/logic/parser/AddressBookParserTest.java, src/test/java/trackup/logic/parser/DeleteEventCommandParserTest.java, src/test/java/trackup/logic/parser/ParserUtilTest.java, src/test/java/trackup/model/AddressBookTest.java, src/test/java/trackup/model/ModelManagerTest.java, src/test/java/trackup/model/event/EventTest.java, src/test/java/trackup/storage/JsonAdaptedEventTest.java, src/test/java/trackup/storage/JsonSerializableAddressBookTest.java, src/test/java/trackup/testutil/EventBuilder.java, src/test/java/trackup/testutil/EventUtil.java, src/test/java/trackup/testutil/TypicalEvents.java
=> task: Improve test coverage for event related classes 

src/main/java/trackup/model/ModelManager.java, src/main/java/trackup/model/util/SampleDataUtil.java, src/main/java/trackup/ui/EventCard.java, src/main/java/trackup/ui/EventListPanel.java, src/main/java/trackup/ui/MainWindow.java, src/main/java/trackup/ui/PersonCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/EventListCard.fxml, src/main/resources/view/EventListPanel.fxml, src/main/resources/view/MainWindow.fxml, src/main/resources/view/PersonListCard.fxml
Closes #110 
- Added EventCard.java and EventListCard.fxml for event card UI component.
- Added EventListPanel.java and EventListPanel.fxml for panel UI component.
============================Update============================
- Added keyboard shortcuts for switching between event and contact lists 
- Added keyboard shortcuts for switching between prev and next week
=> feat: Implement event listing by updating GUI

docs/UserGuide.md
Closes: https://github.com/AY2425S2-CS2103T-F14-4/tp/issues/144
=> docs: Add toggle command to userdoc

src/main/java/trackup/logic/commands/DeleteByCommand.java, src/main/java/trackup/logic/parser/DeleteByCommandParser.java, src/test/java/trackup/logic/commands/DeleteByCommandTest.java, src/test/java/trackup/logic/parser/AddressBookParserTest.java, src/test/java/trackup/logic/parser/DeleteByCommandParserTest.java
Closes: https://github.com/AY2425S2-CS2103T-F14-4/tp/issues/142
=> Bug: Add category parameter to DeleteByCommand

src/main/java/trackup/ui/MainWindow.java, src/main/java/trackup/ui/WeeklyCalendarView.java
Closes #162 
- MainWindow.java : Add addEventFilter to check if command is being typed and keyboard shortcuts now only work when command is not being typed.
- WeeklyCalendarView : Refactor constant value for daylabel and timelabel for better reusability.
=> fix: Edit accelarator logic for week navigation shortcut to work properly

src/main/resources/view/MainWindow.fxml
Closes #170 
- MainWindow.fxml : Edit contacts list window to grow horizontally
- MainWindow.fxml : Set widths for calendar window 
- Minimum window view:
- Maximum (Full) window view:
=> fix: Edit MainWindow.fxml to set sizes for panes with events and contacts

src/main/java/trackup/logic/commands/DeleteByCommand.java, src/main/java/trackup/model/person/Email.java
Closes: https://github.com/AY2425S2-CS2103T-F14-4/tp/issues/204
Closes: https://github.com/AY2425S2-CS2103T-F14-4/tp/issues/143
Closes: https://github.com/AY2425S2-CS2103T-F14-4/tp/issues/180
Closes: https://github.com/AY2425S2-CS2103T-F14-4/tp/issues/168
=> Fix: DeleteByCommand issues found in PE-D

src/main/java/trackup/model/UserPrefs.java, src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json, src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json, src/test/java/trackup/storage/JsonUserPrefsStorageTest.java
- Renamed `addressbook.json` to `trackup.json`
Closes: https://github.com/AY2425S2-CS2103T-F14-4/tp/issues/191
=> refactor: Rename user facing instances of addressbook to trackup

src/main/java/trackup/logic/commands/AddNoteCommand.java, src/main/java/trackup/model/note/Note.java, src/test/java/trackup/logic/commands/AddNoteCommandTest.java
Closes: https://github.com/AY2425S2-CS2103T-F14-4/tp/issues/176
=> Fix: AddNoteCommand issues found in PE-D
